name: Lint Check

on:
  push:

jobs:
  check-formatting:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Install Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm install

      - name: Check code with ESLint
        run: npm run lint